<?php

namespace Desarrolla2\Bundle\BookyBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Desarrolla2\Bundle\BookyBundle\Entity\Author;

/**
 * AuthorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorRepository extends EntityRepository
{
    public function factory($name)
    {
        $em = $this->getEntityManager();

        $author = $this->findOneBy(
            array(
                'name' => $name
            )
        );
        if (!$author) {
            $author = new Author();
            $author->setName($name);
        }

        $em->persist($author);

        return $author;
    }
}
