<?php

namespace Desarrolla2\Bundle\BookyBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;
use Desarrolla2\Bundle\BookyBundle\Entity\Editorial;

/**
 * EditorialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EditorialRepository extends EntityRepository
{
    public function factory($name)
    {
        $em = $this->getEntityManager();

        $editorial = $this->findOneBy(
            array(
                'name' => $name
            )
        );
        if (!$editorial) {
            $editorial = new Editorial();
            $editorial->setName($name);
        }

        $em->persist($editorial);

        return $editorial;
    }
}
