<?php

namespace Desarrolla2\Bundle\BookyBundle\Entity\Repository;

use Desarrolla2\Bundle\BookyBundle\Entity\Suggestion;
use Doctrine\ORM\EntityRepository;

/**
 * SuggestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuggestionRepository extends EntityRepository
{

    public function factory($suggestionUrls)
    {
        $em = $this->getEntityManager();
        $suggestions = array();

        foreach ($suggestionUrls as $suggestionUrl) {
            $suggestion = $this->findOneBy(
                array(
                    'url' => $suggestionUrl
                )
            );
            if (!$suggestion) {
                $suggestion = new Suggestion();
                $suggestion->setUrl($suggestionUrl);
            }
            $suggestions[] = $suggestion;
            $em->persist($suggestion);
        }

        return $suggestions;
    }
}
