<?php

namespace Desarrolla2\Bundle\BookyBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SuggestionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuggestionRepository extends EntityRepository
{
}
